# Generated by Django 5.1.2 on 2024-10-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.URLField(max_length=100)),
                ('github', models.URLField(max_length=100)),
                ('facebook', models.URLField(max_length=100)),
                ('instagram', models.URLField(max_length=100)),
                ('bg_video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
