# Generated by Django 5.1.2 on 2024-10-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('icon', models.ImageField(null=True, upload_to='icons/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skills')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
