# Generated by Django 5.1.2 on 2024-10-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_about_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description_2',
            field=models.TextField(blank=True),
        ),
    ]
