# Generated by Django 5.1.2 on 2024-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_about_description_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(null=True, upload_to='capabilities_icons/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Capabilities',
            },
        ),
    ]
