# Generated by Django 5.1.2 on 2024-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilities',
            name='main_title',
            field=models.CharField(default='Capabilities', max_length=250),
        ),
        migrations.AddField(
            model_name='capabilities',
            name='sub_title',
            field=models.CharField(default='What I can do', max_length=250),
        ),
    ]
