# Generated by Django 5.1.2 on 2024-10-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_capabilities_main_title_capabilities_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capabilities_Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Capabilities Headings',
            },
        ),
        migrations.RemoveField(
            model_name='capabilities',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='capabilities',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='capabilities',
            name='hedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.capabilities_headings'),
        ),
    ]
