# Generated by Django 5.1.2 on 2024-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_education_headings_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institute',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
