# Generated by Django 5.1.2 on 2024-10-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(blank=True),
        ),
    ]
