# Generated by Django 5.1.2 on 2024-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_experience_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='intro_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
