# Generated by Django 5.1.2 on 2024-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_experience_intro_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Projects Headings',
            },
        ),
    ]
