# Generated by Django 5.1.2 on 2024-10-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_projects_project_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project_media',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='media_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projects_headings'),
        ),
    ]
