# Generated by Django 5.1.2 on 2024-10-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_projects_options_remove_project_media_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='media_project',
        ),
        migrations.AddField(
            model_name='project_media',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_project', to='app.projects'),
        ),
    ]
