# Generated by Django 5.1.2 on 2024-10-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_projects_media_project_project_media_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_media',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_project', to='app.projects'),
        ),
    ]
