# Generated by Django 5.1.2 on 2024-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_project_media_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_media',
            name='media',
            field=models.FileField(null=True, upload_to='project_media/', verbose_name=''),
        ),
    ]
