# Generated by Django 5.1 on 2024-10-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_project_media_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates_Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Certificates Headings',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('modal_caption', models.CharField(blank=True, max_length=255)),
                ('verify', models.URLField()),
                ('certificate', models.FileField(null=True, upload_to='certificates/', verbose_name='')),
                ('headings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.certificates_headings')),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
