# Generated by Django 5.1.2 on 2024-10-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_hire_button_picture_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_button_picture',
            name='button_text',
            field=models.CharField(max_length=50),
        ),
    ]
