# Generated by Django 5.1.2 on 2024-10-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_hire_button_picture_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contct_heading_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Contact Headings',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
