# Generated by Django 5.1.2 on 2024-11-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_blog_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog_Heading_Info',
        ),
    ]
