# Generated by Django 5.1.2 on 2024-11-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_blog_blog_heading_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_heading_info',
            options={'verbose_name_plural': 'Blog Heading Info'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_blog', to='app.blog_heading_info'),
        ),
    ]
