# Generated by Django 5.1.2 on 2024-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_blog_heading_info_options_blogs_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
