# Generated by Django 5.1.2 on 2024-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_blogs_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='heading',
            field=models.CharField(max_length=255),
        ),
    ]
