# Generated by Django 5.1.2 on 2024-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job_title_animated_text',
            field=models.TextField(default='Vision Engineer, From Lahore Pakistan'),
        ),
    ]
