# Generated by Django 5.1 on 2024-12-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_person_job_title_animated_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(default='Ahmad Bilal Bhatti', max_length=100)),
                ('platform', models.CharField(default='Medium', max_length=100)),
                ('url', models.URLField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
